-- Exécute ce code dans l'éditeur SQL de Supabase (menu "SQL Editor" à gauche)

-- 1. Création de la table des utilisateurs
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    real_name TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    is_premium INTEGER DEFAULT 0,
    pin TEXT
);

-- 2. Création de la table des messages (historique du chat)
CREATE TABLE IF NOT EXISTS messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Création de la table des profils (personnalisation IA)
CREATE TABLE IF NOT EXISTS profils (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    prenom TEXT,
    situation TEXT,
    defis TEXT,
    objectifs TEXT,
    humeur_generale TEXT,
    preferences TEXT,
    notes_aura TEXT,
    derniere_maj TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Création de la table des humeurs (journal d'humeur)
CREATE TABLE IF NOT EXISTS humeurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER,
    emoji TEXT,
    note TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Création de la table des logs d'accès
CREATE TABLE IF NOT EXISTS logs_acces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    action TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Optionnel : Activer la sécurité RLS (Row Level Security)
-- Permet de sécuriser l'accès aux données si le frontend appelait Supabase directement.
-- Vu que ton backend FastAPI fait le relai, ce n'est pas strictement obligatoire, mais c'est une bonne pratique.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE profils ENABLE ROW LEVEL SECURITY;
ALTER TABLE humeurs ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_acces ENABLE ROW LEVEL SECURITY;

-- Autoriser le backend FastAPI (qui utilise le Service Role ou Anon Key) à tout lire/écrire
CREATE POLICY "Enable all for anon" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON profils FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON humeurs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON logs_acces FOR ALL USING (true) WITH CHECK (true);
